### ISSUE TITLE
` if (creds.client_email.includes("<mailto:")) {`: where do you define creds?

### ISSUE THREAD

**Issue by sampoder** [Onboardbase/securelog-scan#41]
```
❯ sls scan --dir .
Securelog scanning, please wait...
/Users/sam/.config/yarn/global/node_modules/securelog-scan/dist/detectors/gcp/index.js:29
        if (creds.client_email.includes("<mailto:")) {
                               ^

TypeError: Cannot read properties of undefined (reading 'includes')
    at scan (/Users/sam/.config/yarn/global/node_modules/securelog-scan/dist/detectors/gcp/index.js:29:32)
    at /Users/sam/.config/yarn/global/node_modules/securelog-scan/dist/fileScanner.js:26:36
    at Array.map (<anonymous>)
    at processPossibleSecrets (/Users/sam/.config/yarn/global/node_modules/securelog-scan/dist/fileScanner.js:24:33)
    at scanFileForSecrets (/Users/sam/.config/yarn/global/node_modules/securelog-scan/dist/fileScanner.js:15:11)
    at handleFileScanning (/Users/sam/.config/yarn/global/node_modules/securelog-scan/dist/fileScanner.js:104:27)
    at async scanDirectory (/Users/sam/.config/yarn/global/node_modules/securelog-scan/dist/fileScanner.js:80:13)

Node.js v18.20.2
```

Looks like a sweet project, wanted to take it for a spin!

**Comment by iamnasirudeen** [comment]
Hi @sampoder, looking into this already, a patch will be pushed ASAP

**Comment by dantelex** [comment]
@sampoder this issue has been fixed, please update your CLI and try the new version.
